from .test_area_residential_building_list_view import AreaResidentialBuildingListViewTest
from .test_building_garage_list_view import BuildingGarageListViewTest
from .test_building_view import BuildingViewTest
from .test_city_residential_building_list_view import CityResidentialBuildingListViewTest
from .test_non_residential_building_list_view import NonResidentialBuildingListViewTest
from .test_search_name_building_list_view import SearchNameBuildingListViewTest
